# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-27 04:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cameras',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular camera across whole library', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('port', models.CharField(max_length=5)),
                ('login', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('serial_number', models.CharField(max_length=50)),
                ('property_id', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
