# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-02 16:32
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular camera across whole library', primary_key=True, serialize=False)),
                ('message_id', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=250)),
                ('content', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
