# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-07 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_emails_notify'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameras',
            name='video_stream',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
