# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-07 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_cameras_video_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameras',
            name='data_stream',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
