# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-23 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20181011_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='emails',
            name='serial',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
