# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-31 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_cameras_online_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameras',
            name='auth_state',
            field=models.CharField(default='NOT AUTHORIZED', max_length=50),
        ),
    ]
