# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-04 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_cameras_auth_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='agents',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='agents',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cameras',
            name='auth_user',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cameras',
            name='auth_state',
            field=models.CharField(default='AUTHORIZING', max_length=50),
        ),
    ]
