# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-04 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20180904_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
