# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-04 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_properties_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='property_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
