# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-04 14:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_properties_property_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties',
            name='name',
        ),
        migrations.RemoveField(
            model_name='properties',
            name='property_id',
        ),
    ]
