# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-04 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20180904_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='property_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
