# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-05 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20180904_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameras',
            name='property_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
