# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-05 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20181105_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='registered',
            field=models.BooleanField(default=False),
        ),
    ]
