# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-11 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_properties_police'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='trained_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
