# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-10 13:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_users_trained_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='agents',
            name='lastConnection',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
