# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-10 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_agents_lastconnection'),
    ]

    operations = [
        migrations.AddField(
            model_name='agents',
            name='status',
            field=models.CharField(default='offline', max_length=20),
        ),
    ]
