# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-12 07:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_agents_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameras',
            name='lastConnection',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
